language: objective-c
osx_image: xcode10
before_install:
  - gem install xcpretty
  - gem install cocoapods
branches:
  only:
    - master
script:
  - cd Example
  - pod install
  - xcodebuild -version
  - xcodebuild -workspace SnappingStepperExample.xcworkspace -scheme Tests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 8" -configuration Release GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES ONLY_ACTIVE_ARCH=YES test | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash)
